language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install .
    - pip install pytest
script:
    - python -m pytest
    - vegas-lattice --help
    - vegas-lattice describe --help
    - vegas-lattice nanoparticle --help
    - vegas-lattice bulk --help
    - vegas-lattice describe docs/data/sites.dat --lattice-params 8 8 8 --cut 3.52
    - vegas-lattice nanoparticle docs/data/magnetite.json
    - vegas-lattice bulk docs/data/magnetite.json
    - vegas-lattice depleted docs/data/magnetite.json 0.0
    - vegas-lattice depleted docs/data/magnetite.json 0.5
    - vegas-lattice depleted docs/data/magnetite.json 1.0
    - vegas-lattice bulk docs/data/manganite.json
