language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install .
script:
    - vegas-lattice --help
    - vegas-lattice describe --help
    - vegas-lattice nanoparticle --help
    - vegas-lattice bulk --help
    - vegas-lattice describe docs/sites.dat --lattice-params 8 8 8 --cut 3.52
    - vegas-lattice nanoparticle docs/magnetite.json
    - vegas-lattice bulk docs/magnetite.json
